"""T02 — Repository face_media (Postgres/Supabase).

Dùng query tham số hóa + transaction theo nghiệp vụ. Purpose luôn truyền rõ
theo endpoint; service không tin giá trị frontend để đưa dữ liệu search vào
reference (DB giữ FK ghép chặn cuối).
"""

from . import generation, history, identities, media, search, tracklets, validation
from .errors import ConflictError, NotFoundError, PurposeError
from .generation import (
    claim_idempotency_key,
    create_embedding,
    create_generated_image,
    create_generation_job,
    save_idempotency_result,
    set_job_status,
)
from .history import (
    get_session_record,
    list_generation_jobs,
    list_search_runs,
    reconcile_interrupted,
    upsert_session,
)
from .identities import (
    add_assignment,
    bump_revision,
    clear_exemplars,
    create_identity,
    crops_of_tracklet,
    delete_exemplar,
    get_exemplars,
    get_identity,
    get_timeline,
    get_topology,
    list_identities,
    recent_candidates,
    set_exemplar,
    supersede_assignment,
    upsert_topology,
)
from .tracklets import close_tracklet, create_tracklet, get_tracklet, touch_tracklet
from .media import (
    create_asset,
    create_crop,
    create_detection,
    create_frame,
    create_source,
    get_crop_purpose,
    new_id,
)
from .search import (
    add_search_result,
    confirm_search_result,
    create_camera,
    create_ingestion_run,
    create_search_run,
    get_camera,
    get_ingestion_run,
    get_search_run_detail,
    list_cameras,
    list_source_crops,
    list_sources,
    update_ingestion_run,
)

__all__ = [
    "validation",
    "media",
    "generation",
    "search",
    "identities",
    "tracklets",
    "ConflictError",
    "NotFoundError",
    "PurposeError",
    "add_search_result",
    "add_assignment",
    "bump_revision",
    "claim_idempotency_key",
    "clear_exemplars",
    "close_tracklet",
    "confirm_search_result",
    "create_asset",
    "create_camera",
    "create_crop",
    "create_detection",
    "create_embedding",
    "create_frame",
    "create_generated_image",
    "create_generation_job",
    "create_identity",
    "create_ingestion_run",
    "create_search_run",
    "create_source",
    "create_tracklet",
    "crops_of_tracklet",
    "delete_exemplar",
    "get_camera",
    "get_crop_purpose",
    "get_exemplars",
    "get_identity",
    "get_ingestion_run",
    "get_search_run_detail",
    "get_session_record",
    "get_timeline",
    "get_topology",
    "get_tracklet",
    "list_cameras",
    "list_generation_jobs",
    "list_identities",
    "list_search_runs",
    "list_source_crops",
    "list_sources",
    "new_id",
    "recent_candidates",
    "reconcile_interrupted",
    "save_idempotency_result",
    "set_exemplar",
    "set_job_status",
    "supersede_assignment",
    "touch_tracklet",
    "update_ingestion_run",
    "upsert_session",
    "upsert_topology",
]
